name: Generate artifacts for the latest release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  latest-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.latesttag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Get latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Print version
        run: echo Latest version ${{ steps.latesttag.outputs.tag }}

  generate:
    needs: latest-tag
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20
      - uses: actions/checkout@v2.3.3
      - name: Make directory for binaries
        run: mkdir bin
      - name: Build Windows x86_64
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o bin/image-devalue.${{ needs.latest-tag.outputs.tag }}.windows-amd64.exe .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
